AWSTemplateFormatVersion: 2010-09-09
Description: Lake House Step Function component to orchestrate the data flow from the landing zone to the governance account.

Parameters:
  DeploymentRootName:
    Description: Root name of project/component deployment
    Type: String
    Default: lakehouse
  AccountShorthand:
    Description: Abbreviated logical account identifier
    Type: String
    Default: lz
  CompId:
    Description: This templates' component identifier string
    Type: String
    Default: lh-orch
  Env:
    Description: The environment in which the account is being deployed.
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  Region:
    Description: The region for the template to be deployed.
    Type: String
    Default: us-east-2
    AllowedValues:
      - us-east-2
      - us-east-1
  ResourceBucketName:
    Description: The name of the deployment resource bucket.
    Type: String
  StateMachineS3Key:
    Description: The location of the state machine definition in S3.
    Type: String

Resources:

  DataFlowOrchestrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Env}-${DeploymentRootName}-${CompId}-role-${AWS::AccountId}-${Region}"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
                - states.amazonaws.com
                - sts.amazonaws.com
                - lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole'
      Policies:
        - PolicyName: !Sub '${Env}-${DeploymentRootName}-${CompId}-role-policy-${AWS::AccountId}-${Region}'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: 
                  - "s3:*"
                  - "glue:*"
                  - "logs:*"
                  - "lakeformation:*"
                  - "sts:AssumeRole"
                  - "lambda:*"
                Resource:
                  - !Join [ '', ["arn:aws:s3:::*"]]
                  - !Join [ '', ["arn:aws:glue:*:*:", "*"]]
                  - !Join [ '', ["arn:aws:logs:*:*:", "*"]]
                  - "*"

  DataFlowOrchestrator:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub "${Env}-${DeploymentRootName}-${CompId}-datalake-ingestion-workflow-${AWS::AccountId}-${Region}"
      RoleArn: !GetAtt DataFlowOrchestrationRole.Arn
      StateMachineType: STANDARD
      DefinitionS3Location: 
        Bucket: !Ref ResourceBucketName
        Key: !Ref StateMachineS3Key
      DefinitionSubstitutions: 
        LzGlueInitiatorArn: !Sub "arn:aws:lambda:${Region}:396791034774:function:${Env}-${DeploymentRootName}-lz-glue-workflow-initiator-396791034774-${Region}"
        LzGlueStatusCheckerArn: !Sub "arn:aws:lambda:${Region}:396791034774:function:${Env}-${DeploymentRootName}-lz-glue-workflow-status-396791034774-${Region}"
        LzGlueWorkflowName: !Sub "${Env}-${DeploymentRootName}-lz-glue-producer-workflow-396791034774-${Region}"
        LhGlueWorkflowName: !ImportValue LH:IngestionWorkflowName
        GovGlueInitiatorArn: !Sub "arn:aws:lambda:${Region}:488653863644:function:${Env}-${DeploymentRootName}-gov-lf-workflow-initiator-488653863644-${Region}"
        GovGlueStatusCheckerArn: !Sub "arn:aws:lambda:${Region}:488653863644:function:${Env}-${DeploymentRootName}-gov-lf-workflow-status-488653863644-${Region}"
        GovGlueWorkflowName: !Sub "${Env}-${DeploymentRootName}-gov-lf-governance-workflow-488653863644-${Region}"

  