AWSTemplateFormatVersion: 2010-09-09
Description: Landing Zone s3 resources

Parameters:
  DeploymentRootName:
    Description: Root name of project/component deployment
    Type: String
    Default: lakehouse
  AccountShorthand:
    Description: Abbreviated logical account identifier
    Type: String
    Default: gov
  Region:
    Description: The region for the template to be deployed.
    Type: String
    Default: us-east-2
    AllowedValues:
      - us-east-2
      - us-east-1
  CompId:
    Description: This templates' component identifier string
    Type: String
    Default: gov-s3
  Env:
    Description: The environment in which the account is being deployed.
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  ResourceBucketName:
    Description: The name of the deployment resource bucket.
    Type: String

Resources:
  LoggingBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${Env}-${DeploymentRootName}-${CompId}-logs-${AWS::AccountId}-${Region}'
      AccessControl: LogDeliveryWrite
    
  GlueStudioProcessingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Env}-${DeploymentRootName}-${CompId}-glue-tmp-${AWS::AccountId}-${Region}'
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: glue-tmp/
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  ResourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ResourceBucketName}'
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: resources-bucket/
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  ResourceBucketArn:
    Value: !GetAtt ResourceBucket.Arn
    Export:
      Name: !Sub "LZ:ResourceBucketArn"
    Description: "Lake House LZ deployment resources bucket ARN"

  ResourceBucketName:
    Value: !Ref ResourceBucket
    Export:
      Name: !Sub "LZ:ResourceBucketName"
    Description: "Lake House LZ deployment resources bucket name"
