AWSTemplateFormatVersion: 2010-09-09
Description: Landing Zone Account resources

Parameters:
  Environment:
    Description: Which account is the environment being creates
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod

Resources:
  
  LandingZoneBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
              # SSEAlgorithm: 'aws:kms'
              # KMSMasterKeyID: KMS-KEY-ARN