AWSTemplateFormatVersion: 2010-09-09
Description: Consumer template for Athena query resources

Parameters:
  ComponentID:
    Description: This templates' component identifier string
    Type: String
    Default: consumer-athena
  Env:
    Description: The environment in which the account is being deployed.
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod

Resources:
  
  # Athena Role

  # Athena WorkGroup
  MyAthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: !Sub "${Env}-lakehouse-${ComponentID}-athena-wg-1"
      Description: Workgroup for consumer Athena query
      State: ENABLED
      WorkGroupConfiguration:
        BytesScannedCutoffPerQuery: 200000000
        EnforceWorkGroupConfiguration: false
        PublishCloudWatchMetricsEnabled: false
        RequesterPaysEnabled: true
        ResultConfiguration:
          OutputLocation: s3://path/to/my/bucket/

  # Athena Query
  AthenaNamedQuery:
    Type: AWS::Athena::NamedQuery
    Properties:
      Database: "swfnetadata"
      Description: "A query that selects all aggregated data"
      Name: !Sub "${Env}-lakehouse-${ComponentID}-query-1"
      QueryString: >
                    SELECT workflowname, AVG(activitytaskstarted) AS AverageWorkflow
                    FROM swfmetadata
                    WHERE year='17' AND GROUP BY workflowname
                    ORDER BY AverageWorkflow DESC LIMIT 10
