AWSTemplateFormatVersion: 2010-09-09
Description: Consumer catalog template

Parameters:
  ComponentID:
    Description: This templates' component identifier string
    Type: String
    Default: consumer-catalog
  Env:
    Description: The environment in which the account is being deployed.
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod

Resources:

  ConsumerDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub "${Env}-lakehouse-${ComponentID}-glue-database"
        Description: "Catalog database for the crawler"