AWSTemplateFormatVersion: 2010-09-09
Description: Landing Zone Account DataSync resources. We are just syncing 2 S3 buckets in this example

Parameters:
  CompId:
    Description: This templates' component identifier string
    Type: String
    Default: lz-datasync
  Env:
    Description: The environment in which the account is being deployed.
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod

Resources:
  DataSyncSourceBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub "${Env}-lakehouse-${CompId}-datasync-source-bucket"
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  DataSyncBucketRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: "${Env}-lakehouse-${CompId}-datasync-role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: 'datasync.amazonaws.com'
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSDataSyncFullAccess"
      Policies:
        - PolicyName: !Sub "${Env}-${CompId}-lakehouse-role-policy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Action:
                - "s3:GetBucketLocation"
                - "s3:ListBucket"
                - "s3:ListBucketMultipartUploads"
              Effect: Allow
              Resource: "arn:aws:s3:::dev-lakehouse-lz-main-lz-bucket"
            - Action:
                - "s3:AbortMultipartUpload"
                - "s3:DeleteObject"
                - "s3:GetObject"
                - "s3:ListMultipartUploadParts"
                - "s3:PutObjectTagging"
                - "s3:GetObjectTagging"
                - "s3:PutObject"
            Effect: Allow
            Resource: "arn:aws:s3:::dev-lakehouse-lz-main-lz-bucket/*"
        

  DataSyncSourceBucketLocation:
    Type: AWS::DataSync::LocationS3
    Properties: 
      S3BucketArn: !GetAtt DataSyncSourceBucket.Arn
      S3Config: 
        BucketAccessRoleArn: !GetAtt DataSyncBucketRole.Arn

  DataSyncTargetBucketLocation:
    Type: AWS::DataSync::LocationS3
    Properties: 
      S3BucketArn: !ImportValue LZ:LzBucketArn
      S3Config: 
        BucketAccessRoleArn: !GetAtt DataSyncBucketRole.Arn

  DataSyncTask:
    Type: AWS::DataSync::Task
    Properties:
      SourceLocationArn: !GetAtt DataSyncSourceBucketLocation.LocationArn
      DestinationLocationArn: !GetAtt DataSyncTargetBucketLocation.LocationArn