AWSTemplateFormatVersion: 2010-09-09
Description: Landing Zone s3 resources

Parameters:

  ComponentID:
    Description: This templates' component identifier string
    Type: String
    Default: lz-s3

  Env:
    Description: The environment in which the account is being deployed.
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod

  Region:
    Description: The region for the template to be deployed.
    Type: String
    Default: us-east-2
    AllowedValues:
      - us-east-2
      - us-east-1

  ProjectName:
    Type: String
    Description: Project name to link stacks
    Default: consumer-lakeformation

Resources:

  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Env}-lakehouse-${ComponentID}-resources-${AWS::AccountId}-${Region}'
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  
  LandingZoneBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub "${Env}-lakehouse-${ComponentID}-lz-bucket-${AWS::AccountId}-${Region}"
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
              # SSEAlgorithm: 'aws:kms'
              # KMSMasterKeyID: KMS-KEY-ARN

  ProducerBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub "${Env}-lakehouse-${ComponentID}-producer-bucket-${AWS::AccountId}-${Region}"
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  LzBucketArn:
    Value: !GetAtt LandingZoneBucket.Arn
    Export:
      Name: !Sub "LZ:LzBucketArn"
    Description: "Landing Zone bucket ARN"

  DeploymentBucketArn:
    Value: !GetAtt DeploymentBucket.Arn
    Export:
      Name: !Sub "LZ:DeploymentBucketArn"
    Description: "Lake House LZ deployment resources bucket ARN"

  DeploymentBucketNames:
    Value: !Ref DeploymentBucket
    Export:
      Name: !Sub "LZ:DeploymentBucketName"
    Description: "Lake House LZ deployment resources bucket name"
